### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by qu1etusss** [Teselka/imgui_hex_editor#1]
# Hellow my dear frend! 🙋‍♂️. I`m a pro C++ programmer from India <img src="https://github.com/user-attachments/assets/d488c244-5fd0-4949-8f42-2fe291aca18f" width="50">

I am think u can more better make this code! 💯

Here my big brain sugggestions how for u to do it 😊:

Frist 1. PLEASE DONT REPEAT YOURSELF IN CODE! 😉

I see you did same code two times in lines 162 and 173! Why you do this? 🤔 Copy-paste is not your best frend!

Also there are magik numbers in ur code 🪄🧙 Magic is cool, but not in code!

You should change to thing more undrstandable!

I saw many many variable like this

```
128, 32, 0xf0, 0xf
```
Make constant please!! 🙌

Also, also u must use smarter pointers 👆🤓

Ur code no memory safe!!! 

it gonna break PC!!! 😂😂😂 💻💥 BOOM!

**Comment by qu1etusss** [comment]
Don’t worry, many peple make misteaks! 😅

**Comment by qu1etusss** [comment]
i really do like you editor

**Comment by Teselka** [comment]
> I see you did same code two times in lines 162 and 173! Why you do this? 🤔 Copy-paste is not your best frend!

https://github.com/Teselka/imgui_hex_editor/blob/b8cd98a0f654dd6466aa131416848fdbbf67d97f/imgui_hex.cpp#L162

https://github.com/Teselka/imgui_hex_editor/blob/b8cd98a0f654dd6466aa131416848fdbbf67d97f/imgui_hex.cpp#L173

> You should change to thing more undrstandable!
> 
> I saw many many variable like this
> 
> ```
> 128, 32, 0xf0, 0xf
> ```

128 - default stack line buffer size
32 - default stack address buffer size
0xf0 - upper byte mask
0xf - lower byte mask

They're already constants


> Also, also u must use smarter pointers 👆🤓

🤡 

> Ur code no memory safe!!!

There are read/write callbacks to safely read/write memory
